# name: Vue.js CI/CD

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-test-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: "16"

#       - name: Install Dependencies
#         run: npm install

#       - name: Build Vue.js App
#         run: npm run build

#       - name: Deploy with gh-pages
#         run: |
#           git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
#           npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
#         env:
#           GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}